"""JLPT N3 vocabulary seed data, organised by topic."""

JLPT_N3_GROUPS: list[dict] = [
    {
        "title": "JLPT N3 - 日常生活",
        "words": [
            {"term": "生活", "reading": "せいかつ", "definition": "生活", "mnemonic": "「生」活著「活」動，每天的日常就是生活。", "example_sentence": "一人暮らしの生活にやっと慣れてきた。"},
            {"term": "習慣", "reading": "しゅうかん", "definition": "習慣", "mnemonic": "「習」って「慣」れる，反覆做就成了習慣。", "example_sentence": "毎朝ジョギングをする習慣がある。"},
            {"term": "趣味", "reading": "しゅみ", "definition": "興趣、嗜好", "mnemonic": "有「趣」的「味」道，就是讓你感興趣的事。", "example_sentence": "趣味は映画を見ることです。"},
            {"term": "予定", "reading": "よてい", "definition": "預定、計畫", "mnemonic": "「予」め「定」める，事先決定好的計畫。", "example_sentence": "来週の予定はまだ決まっていない。"},
            {"term": "準備", "reading": "じゅんび", "definition": "準備", "mnemonic": "「準」確地「備」好一切，就是做好準備。", "example_sentence": "旅行の準備はもうできましたか。"},
            {"term": "掃除", "reading": "そうじ", "definition": "打掃", "mnemonic": "用掃把「掃」，把髒東西「除」掉。", "example_sentence": "週末に部屋の掃除をした。"},
            {"term": "洗濯", "reading": "せんたく", "definition": "洗衣服", "mnemonic": "「洗」了之後在水裡「濯」（沖洗），就是洗衣服。", "example_sentence": "天気がいいから洗濯物を外に干した。"},
            {"term": "買い物", "reading": "かいもの", "definition": "購物", "mnemonic": "「買」東西（「物」），就是購物。", "example_sentence": "週末にスーパーで買い物をする。"},
            {"term": "引っ越し", "reading": "ひっこし", "definition": "搬家", "mnemonic": "把東西「引」出來「越」過去到新地方，就是搬家。", "example_sentence": "来月、新しいマンションに引っ越しする。"},
            {"term": "届ける", "reading": "とどける", "definition": "送達、遞送", "mnemonic": "東西要「届」（到達）對方手中，就是送達。", "example_sentence": "友達に誕生日プレゼントを届けた。"},
            {"term": "片付ける", "reading": "かたづける", "definition": "整理、收拾", "mnemonic": "把散落的東西一「片」一「片」歸「付」到位。", "example_sentence": "食事の後、テーブルを片付けてください。"},
            {"term": "間に合う", "reading": "まにあう", "definition": "來得及、趕上", "mnemonic": "在時「間」裡面「合」上了，就是來得及。", "example_sentence": "急げば電車に間に合うと思う。"},
            {"term": "慣れる", "reading": "なれる", "definition": "習慣", "mnemonic": "做久了就「慣」了，習以為常。", "example_sentence": "日本の生活にだんだん慣れてきた。"},
            {"term": "暮らす", "reading": "くらす", "definition": "生活、過日子", "mnemonic": "從早到「暮」（傍晚），一整天地過日子。", "example_sentence": "田舎で静かに暮らしたい。"},
            {"term": "近所", "reading": "きんじょ", "definition": "附近、鄰居", "mnemonic": "離得「近」的「所」在，就是附近。", "example_sentence": "近所の人とあまり話したことがない。"},
            {"term": "家賃", "reading": "やちん", "definition": "房租", "mnemonic": "住「家」要付的「賃」金，就是房租。", "example_sentence": "この辺の家賃は月に八万円ぐらいだ。"},
            {"term": "留守", "reading": "るす", "definition": "不在家", "mnemonic": "人「留」在外面沒有「守」在家裡。", "example_sentence": "留守の間に荷物が届いたようだ。"},
            {"term": "日記", "reading": "にっき", "definition": "日記", "mnemonic": "每「日」「記」錄下來的文字。", "example_sentence": "子供のころから日記をつけている。"},
            {"term": "連絡", "reading": "れんらく", "definition": "聯絡", "mnemonic": "「連」續的「絡」（聯繫），保持聯絡。", "example_sentence": "到着したら連絡してください。"},
            {"term": "約束", "reading": "やくそく", "definition": "約定、承諾", "mnemonic": "用繩子「約」（綁）「束」住，代表牢固的承諾。", "example_sentence": "友達と映画を見る約束をした。"},
        ],
    },
    {
        "title": "JLPT N3 - 感情・性格",
        "words": [
            {"term": "気持ち", "reading": "きもち", "definition": "心情、感覺", "mnemonic": "「気」（心氣）所「持」有的狀態，就是心情。", "example_sentence": "今日はとてもいい気持ちだ。"},
            {"term": "感動", "reading": "かんどう", "definition": "感動", "mnemonic": "「感」覺被「動」搖了心靈。", "example_sentence": "あの映画を見て感動して泣いてしまった。"},
            {"term": "感謝", "reading": "かんしゃ", "definition": "感謝", "mnemonic": "心中有「感」，口中說「謝」。", "example_sentence": "いつも助けてくれて感謝しています。"},
            {"term": "心配", "reading": "しんぱい", "definition": "擔心", "mnemonic": "「心」裡在「配」（分配）注意力到擔憂的事上。", "example_sentence": "試験の結果が心配で眠れなかった。"},
            {"term": "不安", "reading": "ふあん", "definition": "不安", "mnemonic": "「不」「安」穩的感覺。", "example_sentence": "将来のことを考えると不安になる。"},
            {"term": "自信", "reading": "じしん", "definition": "自信", "mnemonic": "「自」己「信」任自己。", "example_sentence": "練習を重ねて、自信がついてきた。"},
            {"term": "我慢", "reading": "がまん", "definition": "忍耐", "mnemonic": "「我」要用「慢」慢的心態來忍耐。", "example_sentence": "痛くても我慢してください。"},
            {"term": "幸せ", "reading": "しあわせ", "definition": "幸福", "mnemonic": "「幸」運降臨，就會感到幸福。", "example_sentence": "家族と一緒にいるだけで幸せだ。"},
            {"term": "悲しい", "reading": "かなしい", "definition": "悲傷的", "mnemonic": "心裡覺得「悲」，眼淚快流下來。", "example_sentence": "大好きなペットが死んで悲しい。"},
            {"term": "寂しい", "reading": "さびしい", "definition": "寂寞的", "mnemonic": "「寂」靜無聲，一個人的感覺。", "example_sentence": "一人暮らしは時々寂しい。"},
            {"term": "恥ずかしい", "reading": "はずかしい", "definition": "害羞的、丟臉的", "mnemonic": "感到「恥」辱，臉紅了起來。", "example_sentence": "みんなの前で転んで恥ずかしかった。"},
            {"term": "悔しい", "reading": "くやしい", "definition": "不甘心的", "mnemonic": "後「悔」又不甘心，想要再來一次。", "example_sentence": "試合に負けて本当に悔しい。"},
            {"term": "怒る", "reading": "おこる", "definition": "生氣", "mnemonic": "心中的「怒」火燃燒起來。", "example_sentence": "遅刻したので先生に怒られた。"},
            {"term": "驚く", "reading": "おどろく", "definition": "驚訝", "mnemonic": "突然受到「驚」嚇，嚇了一跳。", "example_sentence": "突然の知らせに驚いた。"},
            {"term": "笑う", "reading": "わらう", "definition": "笑", "mnemonic": "竹子（竹冠）下面「夭」，竹子彎了像在「笑」。", "example_sentence": "彼の冗談を聞いてみんなが笑った。"},
            {"term": "泣く", "reading": "なく", "definition": "哭", "mnemonic": "水（氵）從眼睛裡流出，站立（立）著哭「泣」。", "example_sentence": "感動して思わず泣いてしまった。"},
            {"term": "優しい", "reading": "やさしい", "definition": "溫柔的", "mnemonic": "人（亻）有「憂」心，能體會別人的感受，所以溫柔。", "example_sentence": "彼女はいつも誰にでも優しい。"},
            {"term": "真面目", "reading": "まじめ", "definition": "認真的", "mnemonic": "「真」正面「目」（臉），一本正經的樣子。", "example_sentence": "彼は真面目な学生だ。"},
            {"term": "素直", "reading": "すなお", "definition": "坦率的、老實的", "mnemonic": "「素」（樸素）又「直」（直接），不繞彎子。", "example_sentence": "素直に「ごめんなさい」と言った。"},
            {"term": "性格", "reading": "せいかく", "definition": "性格", "mnemonic": "人的「性」質和「格」調組成了性格。", "example_sentence": "彼とは性格が合わない。"},
        ],
    },
    {
        "title": "JLPT N3 - 仕事・ビジネス",
        "words": [
            {"term": "会議", "reading": "かいぎ", "definition": "會議", "mnemonic": "大家「會」合在一起「議」論事情。", "example_sentence": "午後から大事な会議がある。"},
            {"term": "出張", "reading": "しゅっちょう", "definition": "出差", "mnemonic": "「出」去外地「張」羅工作。", "example_sentence": "来週は大阪に出張する予定だ。"},
            {"term": "経験", "reading": "けいけん", "definition": "經驗", "mnemonic": "「経」歷過並「験」證過的事。", "example_sentence": "海外で働いた経験がありますか。"},
            {"term": "面接", "reading": "めんせつ", "definition": "面試", "mnemonic": "「面」對面地「接」觸，就是面試。", "example_sentence": "明日の面接のためにスーツを準備した。"},
            {"term": "給料", "reading": "きゅうりょう", "definition": "薪水", "mnemonic": "公司「給」你的報「料」（酬勞）。", "example_sentence": "給料は毎月二十五日に振り込まれる。"},
            {"term": "残業", "reading": "ざんぎょう", "definition": "加班", "mnemonic": "「残」（剩餘）時間還在做「業」務。", "example_sentence": "今月は残業が多くて疲れた。"},
            {"term": "相談", "reading": "そうだん", "definition": "商量、諮詢", "mnemonic": "「相」互「談」論，一起商量。", "example_sentence": "困ったことがあったら相談してください。"},
            {"term": "報告", "reading": "ほうこく", "definition": "報告", "mnemonic": "把情況「報」出來「告」訴大家。", "example_sentence": "プロジェクトの進み具合を上司に報告した。"},
            {"term": "説明", "reading": "せつめい", "definition": "說明", "mnemonic": "「説」（說）清楚讓人「明」白。", "example_sentence": "使い方を詳しく説明してください。"},
            {"term": "担当", "reading": "たんとう", "definition": "負責", "mnemonic": "「担」（擔）起「当」（應當）做的責任。", "example_sentence": "このプロジェクトは田中さんが担当している。"},
            {"term": "締め切り", "reading": "しめきり", "definition": "截止日期", "mnemonic": "把門「締」（關）上「切」斷，時間到了就關閉。", "example_sentence": "レポートの締め切りは金曜日です。"},
            {"term": "契約", "reading": "けいやく", "definition": "契約", "mnemonic": "用文書「契」定「約」定的內容。", "example_sentence": "新しい会社と契約を結んだ。"},
            {"term": "売上", "reading": "うりあげ", "definition": "營業額", "mnemonic": "「売」（賣）出去後「上」報的金額。", "example_sentence": "今月の売上は先月より増えた。"},
            {"term": "取引", "reading": "とりひき", "definition": "交易", "mnemonic": "互相「取」得和「引」出（交換），就是交易。", "example_sentence": "その会社とは長年取引がある。"},
            {"term": "製品", "reading": "せいひん", "definition": "產品", "mnemonic": "「製」造出來的「品」物。", "example_sentence": "この製品は品質が非常に高い。"},
            {"term": "企業", "reading": "きぎょう", "definition": "企業", "mnemonic": "「企」劃「業」務的組織。", "example_sentence": "多くの企業がAI技術を導入している。"},
            {"term": "社員", "reading": "しゃいん", "definition": "公司職員", "mnemonic": "公「社」的成「員」。", "example_sentence": "この会社には約五百人の社員がいる。"},
            {"term": "上司", "reading": "じょうし", "definition": "上司", "mnemonic": "在「上」面「司」（管理）你的人。", "example_sentence": "上司に相談してから決めます。"},
            {"term": "部下", "reading": "ぶか", "definition": "部下", "mnemonic": "在部門之「下」的人。", "example_sentence": "部下の意見もしっかり聞くべきだ。"},
            {"term": "同僚", "reading": "どうりょう", "definition": "同事", "mnemonic": "「同」じ職場の仲間（「僚」）。", "example_sentence": "同僚と一緒にランチを食べた。"},
        ],
    },
    {
        "title": "JLPT N3 - 自然・天気",
        "words": [
            {"term": "天気予報", "reading": "てんきよほう", "definition": "天氣預報", "mnemonic": "「天気」を「予」め「報」じる。", "example_sentence": "天気予報によると明日は雨だそうだ。"},
            {"term": "台風", "reading": "たいふう", "definition": "颱風", "mnemonic": "「台」灣常來的大「風」，就是颱風。", "example_sentence": "台風が近づいているので気をつけてください。"},
            {"term": "地震", "reading": "じしん", "definition": "地震", "mnemonic": "「地」面「震」動。", "example_sentence": "昨夜、大きな地震があった。"},
            {"term": "湿気", "reading": "しっけ", "definition": "濕氣", "mnemonic": "空氣中的水分讓「気」變得「湿」。", "example_sentence": "梅雨の時期は湿気がひどい。"},
            {"term": "気温", "reading": "きおん", "definition": "氣溫", "mnemonic": "空「気」的「温」度。", "example_sentence": "今日の気温は三十五度を超えた。"},
            {"term": "梅雨", "reading": "つゆ", "definition": "梅雨", "mnemonic": "「梅」子成熟的季節下的「雨」。", "example_sentence": "六月は梅雨の季節で雨が多い。"},
            {"term": "晴れる", "reading": "はれる", "definition": "放晴", "mnemonic": "太「日」出來，天氣變「青」，就是「晴」。", "example_sentence": "午後から晴れるらしい。"},
            {"term": "曇る", "reading": "くもる", "definition": "陰天", "mnemonic": "太陽被雲遮住，天空變得灰「曇」曇的。", "example_sentence": "朝から空が曇っている。"},
            {"term": "吹く", "reading": "ふく", "definition": "吹（風）", "mnemonic": "口（口）裡「欠」（呼氣），用嘴巴吹。", "example_sentence": "今日は強い風が吹いている。"},
            {"term": "凍る", "reading": "こおる", "definition": "結冰", "mnemonic": "水遇到冰點就「凍」結了。", "example_sentence": "冬になると湖の水が凍る。"},
            {"term": "咲く", "reading": "さく", "definition": "（花）開", "mnemonic": "口（口）張開笑（关），花朵綻放像在笑。", "example_sentence": "春になると桜が咲く。"},
            {"term": "枯れる", "reading": "かれる", "definition": "枯萎", "mnemonic": "樹木（木）變「古」老，就會枯萎。", "example_sentence": "水をやらなかったので花が枯れてしまった。"},
            {"term": "森", "reading": "もり", "definition": "森林", "mnemonic": "三棵「木」在一起，就是茂密的「森」林。", "example_sentence": "森の中を散歩するのが好きだ。"},
            {"term": "湖", "reading": "みずうみ", "definition": "湖", "mnemonic": "水（氵）邊的「古」老「月」光倒映之處。", "example_sentence": "湖の水がきれいに輝いていた。"},
            {"term": "島", "reading": "しま", "definition": "島", "mnemonic": "「山」被水圍繞，鳥（鳥）棲息的地方。", "example_sentence": "沖縄は美しい島がたくさんある。"},
            {"term": "砂", "reading": "すな", "definition": "沙子", "mnemonic": "石（石）頭磨「少」了就變成細小的砂。", "example_sentence": "子供たちが砂で遊んでいる。"},
            {"term": "石", "reading": "いし", "definition": "石頭", "mnemonic": "崖（厂）下有一「口」大石頭。", "example_sentence": "川で丸い石を拾った。"},
            {"term": "影", "reading": "かげ", "definition": "影子", "mnemonic": "太「日」照在「京」都的建築上留下影子。", "example_sentence": "夕方になると影が長くなる。"},
            {"term": "環境", "reading": "かんきょう", "definition": "環境", "mnemonic": "「環」繞在「境」（周圍）的一切條件。", "example_sentence": "環境を守るためにゴミを減らそう。"},
            {"term": "自然", "reading": "しぜん", "definition": "自然", "mnemonic": "「自」己「然」（本來的樣子），大自然的原貌。", "example_sentence": "自然の中でリラックスしたい。"},
        ],
    },
    {
        "title": "JLPT N3 - 交通・移動",
        "words": [
            {"term": "交通", "reading": "こうつう", "definition": "交通", "mnemonic": "人和車互相「交」叉「通」行。", "example_sentence": "この辺は交通の便がいい。"},
            {"term": "出発", "reading": "しゅっぱつ", "definition": "出發", "mnemonic": "「出」去「発」（發）動旅程。", "example_sentence": "飛行機は午前十時に出発する。"},
            {"term": "到着", "reading": "とうちゃく", "definition": "到達", "mnemonic": "「到」了目的地並且「着」（附著）陸。", "example_sentence": "空港に無事到着した。"},
            {"term": "乗り換え", "reading": "のりかえ", "definition": "轉車", "mnemonic": "從一台車「乗」（搭）下來「換」另一台。", "example_sentence": "新宿で地下鉄に乗り換えてください。"},
            {"term": "片道", "reading": "かたみち", "definition": "單程", "mnemonic": "只有「片」面（一邊）的「道」路，單方向。", "example_sentence": "片道の切符を一枚ください。"},
            {"term": "往復", "reading": "おうふく", "definition": "往返", "mnemonic": "「往」（去）了又「復」（回來）。", "example_sentence": "往復切符の方が安い。"},
            {"term": "通勤", "reading": "つうきん", "definition": "通勤", "mnemonic": "「通」過交通工具去上「勤」（班）。", "example_sentence": "毎日電車で通勤している。"},
            {"term": "渋滞", "reading": "じゅうたい", "definition": "塞車", "mnemonic": "車子走得很「渋」（澀），「滞」（停滯）不前。", "example_sentence": "朝の渋滞で会社に遅れた。"},
            {"term": "駐車場", "reading": "ちゅうしゃじょう", "definition": "停車場", "mnemonic": "「駐」（停）「車」的「場」所。", "example_sentence": "駐車場はもう満車だった。"},
            {"term": "信号", "reading": "しんごう", "definition": "紅綠燈", "mnemonic": "發出「信」息的「号」（號）誌。", "example_sentence": "信号が赤に変わったので止まった。"},
            {"term": "横断歩道", "reading": "おうだんほどう", "definition": "斑馬線", "mnemonic": "「横」向「断」（切斷）馬路的「歩」行「道」。", "example_sentence": "横断歩道を渡るときは左右を確認しよう。"},
            {"term": "歩道", "reading": "ほどう", "definition": "人行道", "mnemonic": "走「歩」（步）的「道」路。", "example_sentence": "歩道を自転車で走ってはいけない。"},
            {"term": "通る", "reading": "とおる", "definition": "通過", "mnemonic": "從一個地方「通」過去。", "example_sentence": "毎日この道を通って学校に行く。"},
            {"term": "曲がる", "reading": "まがる", "definition": "轉彎", "mnemonic": "道路不是直的而是「曲」的。", "example_sentence": "次の角を右に曲がってください。"},
            {"term": "戻る", "reading": "もどる", "definition": "返回", "mnemonic": "「戸」（門）口等著你回來，返回原處。", "example_sentence": "忘れ物をしたので家に戻った。"},
            {"term": "届く", "reading": "とどく", "definition": "送到、抵達", "mnemonic": "東西一層一層（尸）到「由」你手中，送達了。", "example_sentence": "注文した本がやっと届いた。"},
            {"term": "迷う", "reading": "まよう", "definition": "迷路、猶豫", "mnemonic": "在十字路口（辶）不知道走哪條「米」路。", "example_sentence": "道に迷って三十分も遅れた。"},
            {"term": "乗客", "reading": "じょうきゃく", "definition": "乘客", "mnemonic": "「乗」（搭乘）交通工具的「客」人。", "example_sentence": "電車の乗客が急に増えた。"},
            {"term": "運転", "reading": "うんてん", "definition": "駕駛", "mnemonic": "「運」用手來「転」（轉）動方向盤。", "example_sentence": "長時間の運転は疲れるので休憩しよう。"},
            {"term": "免許", "reading": "めんきょ", "definition": "駕照、許可證", "mnemonic": "被「免」除限制而獲得「許」可。", "example_sentence": "十八歳になったら運転免許を取りたい。"},
        ],
    },
    {
        "title": "JLPT N3 - 健康・体",
        "words": [
            {"term": "健康", "reading": "けんこう", "definition": "健康", "mnemonic": "身體「健」壯又安「康」。", "example_sentence": "健康のために毎日運動している。"},
            {"term": "体調", "reading": "たいちょう", "definition": "身體狀況", "mnemonic": "「体」（身體）的「調」子（狀態）。", "example_sentence": "最近体調があまりよくない。"},
            {"term": "症状", "reading": "しょうじょう", "definition": "症狀", "mnemonic": "病「症」呈現出的「状」態。", "example_sentence": "どんな症状がありますか。"},
            {"term": "熱", "reading": "ねつ", "definition": "發燒、熱", "mnemonic": "身體像被火燒一樣「熱」。", "example_sentence": "朝から三十八度の熱がある。"},
            {"term": "咳", "reading": "せき", "definition": "咳嗽", "mnemonic": "「口」裡發出「亥」的聲音，咳咳咳。", "example_sentence": "咳が止まらないので病院に行った。"},
            {"term": "風邪", "reading": "かぜ", "definition": "感冒", "mnemonic": "「風」吹來了「邪」氣，就容易感冒。", "example_sentence": "風邪を引いたので今日は休みます。"},
            {"term": "怪我", "reading": "けが", "definition": "受傷", "mnemonic": "受傷了會覺得「怪」，「我」怎麼會弄傷自己。", "example_sentence": "サッカーの試合で足に怪我をした。"},
            {"term": "治る", "reading": "なおる", "definition": "痊癒", "mnemonic": "水（氵）在「台」上流過，沖洗傷口使其痊癒。", "example_sentence": "薬を飲んだら風邪がすぐ治った。"},
            {"term": "治す", "reading": "なおす", "definition": "治療", "mnemonic": "主動去「治」好疾病（他動詞）。", "example_sentence": "この病気は手術で治すことができる。"},
            {"term": "薬", "reading": "くすり", "definition": "藥", "mnemonic": "草（艹）能帶來「楽」（快樂），草藥治病。", "example_sentence": "食後にこの薬を飲んでください。"},
            {"term": "注射", "reading": "ちゅうしゃ", "definition": "打針", "mnemonic": "「注」入液體「射」進身體。", "example_sentence": "インフルエンザの注射を受けた。"},
            {"term": "検査", "reading": "けんさ", "definition": "檢查", "mnemonic": "「検」（檢）驗並「査」（查）看結果。", "example_sentence": "年に一回健康検査を受けている。"},
            {"term": "入院", "reading": "にゅういん", "definition": "住院", "mnemonic": "「入」（進入）醫「院」。", "example_sentence": "手術のため二週間入院した。"},
            {"term": "退院", "reading": "たいいん", "definition": "出院", "mnemonic": "「退」出醫「院」。", "example_sentence": "来週退院できると言われた。"},
            {"term": "診察", "reading": "しんさつ", "definition": "看診", "mnemonic": "醫生「診」斷並「察」看病情。", "example_sentence": "午前中に病院で診察を受けた。"},
            {"term": "血", "reading": "ち", "definition": "血", "mnemonic": "皿（器皿）裡盛著紅色的液體，那是「血」。", "example_sentence": "指を切って血が出た。"},
            {"term": "骨", "reading": "ほね", "definition": "骨頭", "mnemonic": "身體裡面支撐的硬「骨」架。", "example_sentence": "転んで足の骨を折ってしまった。"},
            {"term": "筋肉", "reading": "きんにく", "definition": "肌肉", "mnemonic": "竹（筋）一樣有彈性的「肉」。", "example_sentence": "運動の後は筋肉が痛い。"},
            {"term": "疲れる", "reading": "つかれる", "definition": "疲勞", "mnemonic": "生病（疒）的皮膚一樣沒有力氣，感到「疲」憊。", "example_sentence": "今日は一日中歩いて疲れた。"},
            {"term": "痩せる", "reading": "やせる", "definition": "變瘦", "mnemonic": "生病（疒）到身體都變薄（叟）了，就是瘦了。", "example_sentence": "最近五キロ痩せた。"},
        ],
    },
    {
        "title": "JLPT N3 - 食事・料理",
        "words": [
            {"term": "材料", "reading": "ざいりょう", "definition": "材料", "mnemonic": "做菜需要的「材」木般基本的原「料」。", "example_sentence": "カレーの材料を買いにスーパーに行った。"},
            {"term": "調味料", "reading": "ちょうみりょう", "definition": "調味料", "mnemonic": "「調」整「味」道的原「料」。", "example_sentence": "塩や醤油などの調味料を使って味付けする。"},
            {"term": "味", "reading": "あじ", "definition": "味道", "mnemonic": "嘴巴（口）嘗「未」知的食物，品嚐「味」道。", "example_sentence": "この料理は味が薄い。"},
            {"term": "匂い", "reading": "におい", "definition": "氣味", "mnemonic": "用鼻子（匕）感受到的氣味。", "example_sentence": "パンが焼けるいい匂いがする。"},
            {"term": "栄養", "reading": "えいよう", "definition": "營養", "mnemonic": "讓身體「栄」（繁榮）並「養」育成長的元素。", "example_sentence": "栄養のバランスを考えて食事をしよう。"},
            {"term": "焼く", "reading": "やく", "definition": "烤、煎", "mnemonic": "用「火」把東西烤到變色（堯）。", "example_sentence": "庭でお肉を焼いてバーベキューをした。"},
            {"term": "煮る", "reading": "にる", "definition": "煮", "mnemonic": "在「火」上把食物和「者」（各種東西）一起煮。", "example_sentence": "野菜を柔らかくなるまで煮る。"},
            {"term": "揚げる", "reading": "あげる", "definition": "炸", "mnemonic": "用手（扌）把食物從油裡「揚」（提）起來。", "example_sentence": "鶏肉を揚げてからあげを作った。"},
            {"term": "混ぜる", "reading": "まぜる", "definition": "攪拌", "mnemonic": "用水（氵）把各種東西「混」在一起攪拌。", "example_sentence": "卵と砂糖をよく混ぜてください。"},
            {"term": "沸かす", "reading": "わかす", "definition": "煮沸", "mnemonic": "水（氵）「弗」（沸騰），把水燒開。", "example_sentence": "お茶を入れるためにお湯を沸かした。"},
            {"term": "冷ます", "reading": "さます", "definition": "放涼", "mnemonic": "讓「冷」氣進來，把熱的東西放涼。", "example_sentence": "スープが熱いから少し冷ましてから飲もう。"},
            {"term": "冷凍", "reading": "れいとう", "definition": "冷凍", "mnemonic": "「冷」到「凍」住，保存食物的方法。", "example_sentence": "残ったご飯を冷凍しておいた。"},
            {"term": "賞味期限", "reading": "しょうみきげん", "definition": "保存期限", "mnemonic": "能「賞」（享受）「味」道的「期」間「限」制。", "example_sentence": "賞味期限が切れた牛乳は飲まない方がいい。"},
            {"term": "お代わり", "reading": "おかわり", "definition": "再來一碗", "mnemonic": "用新的一碗來「代」替（「替わり」）空碗。", "example_sentence": "ご飯のお代わりをお願いします。"},
            {"term": "注文", "reading": "ちゅうもん", "definition": "點餐、訂購", "mnemonic": "「注」意看菜單上的「文」字來點餐。", "example_sentence": "ラーメンを一つ注文した。"},
            {"term": "割引", "reading": "わりびき", "definition": "折扣", "mnemonic": "把價格「割」（切）開再「引」（拉）下來。", "example_sentence": "このクーポンで二十パーセント割引になる。"},
            {"term": "レシピ", "reading": "レシピ", "definition": "食譜", "mnemonic": "recipe 的日語外來語發音。", "example_sentence": "ネットで簡単なレシピを探した。"},
            {"term": "弁当", "reading": "べんとう", "definition": "便當", "mnemonic": "方「便」「当」（適當）的餐盒。", "example_sentence": "毎朝自分で弁当を作っている。"},
            {"term": "丼", "reading": "どんぶり", "definition": "蓋飯", "mnemonic": "「井」裡面有一點（丶），像碗裡裝滿飯和料。", "example_sentence": "お昼は牛丼を食べた。"},
            {"term": "漬物", "reading": "つけもの", "definition": "醃菜", "mnemonic": "用水（氵）「漬」（浸泡）的食「物」。", "example_sentence": "日本の食事には漬物がよく出る。"},
        ],
    },
    {
        "title": "JLPT N3 - 社会・文化",
        "words": [
            {"term": "社会", "reading": "しゃかい", "definition": "社會", "mnemonic": "人們在「社」（組織）裡「会」（聚集），形成社會。", "example_sentence": "大学を卒業して社会に出た。"},
            {"term": "政治", "reading": "せいじ", "definition": "政治", "mnemonic": "用「政」策來「治」理國家。", "example_sentence": "若い人も政治に関心を持つべきだ。"},
            {"term": "経済", "reading": "けいざい", "definition": "經濟", "mnemonic": "「経」（經）營並「済」（濟助）民生。", "example_sentence": "日本の経済は少しずつ回復している。"},
            {"term": "法律", "reading": "ほうりつ", "definition": "法律", "mnemonic": "「法」則和「律」令，社會的規範。", "example_sentence": "法律を守ることは市民の義務だ。"},
            {"term": "選挙", "reading": "せんきょ", "definition": "選舉", "mnemonic": "「選」擇並「挙」（舉）出代表。", "example_sentence": "来月選挙があるので投票に行く。"},
            {"term": "国際", "reading": "こくさい", "definition": "國際", "mnemonic": "「国」與國之「際」（之間）的關係。", "example_sentence": "国際交流のイベントに参加した。"},
            {"term": "人口", "reading": "じんこう", "definition": "人口", "mnemonic": "數算「人」的「口」數。", "example_sentence": "この町の人口は約十万人だ。"},
            {"term": "文化", "reading": "ぶんか", "definition": "文化", "mnemonic": "「文」明教「化」的成果。", "example_sentence": "日本の文化に興味がある。"},
            {"term": "伝統", "reading": "でんとう", "definition": "傳統", "mnemonic": "「伝」（傳）承下來「統」一的做法。", "example_sentence": "この祭りは長い伝統がある。"},
            {"term": "祭り", "reading": "まつり", "definition": "祭典", "mnemonic": "用「肉」（月）和手（又）在「示」（神壇）前舉行祭典。", "example_sentence": "夏祭りで花火を見た。"},
            {"term": "宗教", "reading": "しゅうきょう", "definition": "宗教", "mnemonic": "人們「宗」仰的「教」義。", "example_sentence": "世界にはさまざまな宗教がある。"},
            {"term": "歴史", "reading": "れきし", "definition": "歷史", "mnemonic": "「歴」（經歷）過的「史」（記載）。", "example_sentence": "歴史を学ぶことは大切だ。"},
            {"term": "平和", "reading": "へいわ", "definition": "和平", "mnemonic": "「平」穩又「和」諧的狀態。", "example_sentence": "世界の平和を願っている。"},
            {"term": "戦争", "reading": "せんそう", "definition": "戰爭", "mnemonic": "互相「戦」（戰）鬥「争」奪。", "example_sentence": "戦争のない世界になってほしい。"},
            {"term": "事件", "reading": "じけん", "definition": "事件", "mnemonic": "發生的「事」情成為「件」（案件）。", "example_sentence": "昨日この近くで事件があった。"},
            {"term": "事故", "reading": "じこ", "definition": "事故", "mnemonic": "出了「事」的「故」（緣故），意外發生了。", "example_sentence": "交通事故で電車が遅れた。"},
            {"term": "犯罪", "reading": "はんざい", "definition": "犯罪", "mnemonic": "「犯」了「罪」行。", "example_sentence": "この地域は犯罪が少なくて安全だ。"},
            {"term": "規則", "reading": "きそく", "definition": "規則", "mnemonic": "「規」定的法「則」。", "example_sentence": "学校の規則を守らなければならない。"},
            {"term": "権利", "reading": "けんり", "definition": "權利", "mnemonic": "「権」（權）力帶來的「利」益。", "example_sentence": "すべての人に教育を受ける権利がある。"},
            {"term": "義務", "reading": "ぎむ", "definition": "義務", "mnemonic": "正「義」的「務」（任務），應盡的責任。", "example_sentence": "税金を納めるのは国民の義務だ。"},
        ],
    },
    {
        "title": "JLPT N3 - 教育・学習",
        "words": [
            {"term": "教育", "reading": "きょういく", "definition": "教育", "mnemonic": "「教」導並「育」成人才。", "example_sentence": "子供の教育にはお金がかかる。"},
            {"term": "授業", "reading": "じゅぎょう", "definition": "上課", "mnemonic": "老師「授」予知識的「業」務。", "example_sentence": "今日の授業はとても面白かった。"},
            {"term": "講義", "reading": "こうぎ", "definition": "講座", "mnemonic": "「講」述「義」理和知識。", "example_sentence": "大学で経済学の講義を受けている。"},
            {"term": "研究", "reading": "けんきゅう", "definition": "研究", "mnemonic": "「研」磨並「究」（追究）真理。", "example_sentence": "大学院で日本語教育を研究している。"},
            {"term": "論文", "reading": "ろんぶん", "definition": "論文", "mnemonic": "「論」述觀點的「文」章。", "example_sentence": "卒業論文のテーマがまだ決まらない。"},
            {"term": "卒業", "reading": "そつぎょう", "definition": "畢業", "mnemonic": "完「卒」（結束）學「業」。", "example_sentence": "来年の三月に大学を卒業する。"},
            {"term": "入学", "reading": "にゅうがく", "definition": "入學", "mnemonic": "「入」（進入）「学」校。", "example_sentence": "四月に小学校に入学した。"},
            {"term": "試験", "reading": "しけん", "definition": "考試", "mnemonic": "「試」著去「験」（驗）證學習成果。", "example_sentence": "来週の試験のために毎日勉強している。"},
            {"term": "成績", "reading": "せいせき", "definition": "成績", "mnemonic": "達「成」的「績」（業績）。", "example_sentence": "今学期の成績はとてもよかった。"},
            {"term": "合格", "reading": "ごうかく", "definition": "及格、合格", "mnemonic": "「合」乎標準的「格」（資格）。", "example_sentence": "JLPT N3に合格した。"},
            {"term": "不合格", "reading": "ふごうかく", "definition": "不及格", "mnemonic": "「不」符「合」標準的「格」。", "example_sentence": "残念ながら不合格だった。"},
            {"term": "復習", "reading": "ふくしゅう", "definition": "複習", "mnemonic": "「復」（再次）「習」學過的內容。", "example_sentence": "授業の後は必ず復習する。"},
            {"term": "予習", "reading": "よしゅう", "definition": "預習", "mnemonic": "「予」（預）先「習」學新內容。", "example_sentence": "明日の授業の予習をしておこう。"},
            {"term": "暗記", "reading": "あんき", "definition": "背誦、記住", "mnemonic": "在「暗」處也能「記」住，就是背下來了。", "example_sentence": "単語を暗記するのが苦手だ。"},
            {"term": "翻訳", "reading": "ほんやく", "definition": "翻譯", "mnemonic": "「翻」開書本「訳」（譯）成另一種語言。", "example_sentence": "この本を日本語に翻訳した。"},
            {"term": "文法", "reading": "ぶんぽう", "definition": "文法", "mnemonic": "寫「文」章的「法」則。", "example_sentence": "日本語の文法は難しい。"},
            {"term": "発音", "reading": "はつおん", "definition": "發音", "mnemonic": "「発」出「音」（聲音）。", "example_sentence": "日本語の発音をもっと練習したい。"},
            {"term": "意味", "reading": "いみ", "definition": "意思", "mnemonic": "話語中的「意」思和「味」道（含義）。", "example_sentence": "この言葉の意味がわからない。"},
            {"term": "例", "reading": "れい", "definition": "例子", "mnemonic": "站在人（亻）旁邊「列」出來的就是範「例」。", "example_sentence": "例を挙げて説明してください。"},
            {"term": "知識", "reading": "ちしき", "definition": "知識", "mnemonic": "「知」道並能「識」別的能力。", "example_sentence": "幅広い知識を身につけたい。"},
        ],
    },
    {
        "title": "JLPT N3 - 動詞①",
        "words": [
            {"term": "集める", "reading": "あつめる", "definition": "收集", "mnemonic": "把散落的東西「集」中在一起。", "example_sentence": "世界中の切手を集めている。"},
            {"term": "届ける", "reading": "とどける", "definition": "送達", "mnemonic": "讓東西「届」（到達）對方手中。", "example_sentence": "忘れ物を届けてくれてありがとう。"},
            {"term": "伝える", "reading": "つたえる", "definition": "傳達", "mnemonic": "把訊息「伝」（傳）遞給別人。", "example_sentence": "大事なことを彼に伝えてください。"},
            {"term": "育てる", "reading": "そだてる", "definition": "培養、養育", "mnemonic": "讓小生命成長，用心「育」成。", "example_sentence": "ベランダでトマトを育てている。"},
            {"term": "比べる", "reading": "くらべる", "definition": "比較", "mnemonic": "把兩個東西放在一起「比」一比。", "example_sentence": "二つの商品を比べてから買う。"},
            {"term": "調べる", "reading": "しらべる", "definition": "調查", "mnemonic": "仔細地「調」查研究。", "example_sentence": "インターネットで調べてみよう。"},
            {"term": "確かめる", "reading": "たしかめる", "definition": "確認", "mnemonic": "讓事情變得「確」實可靠。", "example_sentence": "出かける前に鍵を確かめた。"},
            {"term": "見つける", "reading": "みつける", "definition": "發現、找到", "mnemonic": "用眼睛「見」到並找到目標。", "example_sentence": "やっと探していた本を見つけた。"},
            {"term": "捨てる", "reading": "すてる", "definition": "丟棄", "mnemonic": "用手（扌）把不要的東西丟「舎」（捨）棄。", "example_sentence": "古い服を捨てることにした。"},
            {"term": "倒れる", "reading": "たおれる", "definition": "倒下", "mnemonic": "人（亻）到（到）了極限就「倒」下。", "example_sentence": "過労で倒れて病院に運ばれた。"},
            {"term": "壊れる", "reading": "こわれる", "definition": "壞掉", "mnemonic": "土做的東西容易「壊」（壞）掉。", "example_sentence": "洗濯機が壊れてしまった。"},
            {"term": "壊す", "reading": "こわす", "definition": "弄壞", "mnemonic": "主動把東西「壊」（弄壞）。", "example_sentence": "子供がおもちゃを壊してしまった。"},
            {"term": "直す", "reading": "なおす", "definition": "修理、改正", "mnemonic": "把歪的弄「直」回來。", "example_sentence": "壊れた時計を直してもらった。"},
            {"term": "建てる", "reading": "たてる", "definition": "建造", "mnemonic": "在地上「建」起建築物。", "example_sentence": "来年新しい家を建てる予定だ。"},
            {"term": "運ぶ", "reading": "はこぶ", "definition": "搬運", "mnemonic": "用力「運」送東西到別處。", "example_sentence": "重い荷物を二階まで運んだ。"},
            {"term": "落とす", "reading": "おとす", "definition": "弄掉", "mnemonic": "讓東西「落」下去。", "example_sentence": "うっかりスマホを落としてしまった。"},
            {"term": "拾う", "reading": "ひろう", "definition": "撿起", "mnemonic": "用手（扌）把東西從地上「合」起來。", "example_sentence": "道に落ちていた財布を拾った。"},
            {"term": "触る", "reading": "さわる", "definition": "觸摸", "mnemonic": "用手去接「触」。", "example_sentence": "展示品に触らないでください。"},
            {"term": "引く", "reading": "ひく", "definition": "拉", "mnemonic": "用弓（弓）一樣的力量「引」（拉）。", "example_sentence": "このドアは引いて開けてください。"},
            {"term": "押す", "reading": "おす", "definition": "推、按", "mnemonic": "用手指按「甲」，就是「押」（推按）。", "example_sentence": "エレベーターのボタンを押した。"},
        ],
    },
    {
        "title": "JLPT N3 - 動詞②",
        "words": [
            {"term": "参加する", "reading": "さんかする", "definition": "參加", "mnemonic": "「参」與並「加」入活動。", "example_sentence": "友達の結婚式に参加した。"},
            {"term": "紹介する", "reading": "しょうかいする", "definition": "介紹", "mnemonic": "把人「紹」（引）出來並「介」入認識。", "example_sentence": "新しいメンバーをみんなに紹介した。"},
            {"term": "利用する", "reading": "りようする", "definition": "利用", "mnemonic": "有「利」地「用」（使用）資源。", "example_sentence": "図書館をよく利用している。"},
            {"term": "輸出する", "reading": "ゆしゅつする", "definition": "出口", "mnemonic": "「輸」送「出」去到國外。", "example_sentence": "日本は車を多くの国に輸出している。"},
            {"term": "輸入する", "reading": "ゆにゅうする", "definition": "進口", "mnemonic": "從國外「輸」送「入」（進）來。", "example_sentence": "この果物は海外から輸入されたものだ。"},
            {"term": "成功する", "reading": "せいこうする", "definition": "成功", "mnemonic": "事情「成」就了「功」業。", "example_sentence": "長年の努力がついに成功した。"},
            {"term": "失敗する", "reading": "しっぱいする", "definition": "失敗", "mnemonic": "「失」去了成功，遭遇「敗」北。", "example_sentence": "初めての料理は失敗してしまった。"},
            {"term": "賛成する", "reading": "さんせいする", "definition": "贊成", "mnemonic": "「賛」同並「成」立意見。", "example_sentence": "その提案に賛成します。"},
            {"term": "反対する", "reading": "はんたいする", "definition": "反對", "mnemonic": "站在「反」面「対」（對）立。", "example_sentence": "その計画には反対する人が多い。"},
            {"term": "注意する", "reading": "ちゅういする", "definition": "注意", "mnemonic": "「注」入「意」識，集中精神。", "example_sentence": "車に注意して道を渡ってください。"},
            {"term": "発見する", "reading": "はっけんする", "definition": "發現", "mnemonic": "「発」（發）出並「見」到新事物。", "example_sentence": "新しい星が発見された。"},
            {"term": "発明する", "reading": "はつめいする", "definition": "發明", "mnemonic": "「発」想出「明」亮的新點子。", "example_sentence": "エジソンは電球を発明した。"},
            {"term": "表現する", "reading": "ひょうげんする", "definition": "表現", "mnemonic": "把內心「表」達並「現」（呈現）出來。", "example_sentence": "自分の気持ちを言葉で表現するのは難しい。"},
            {"term": "想像する", "reading": "そうぞうする", "definition": "想像", "mnemonic": "「想」著腦中的「像」（畫面）。", "example_sentence": "十年後の自分を想像してみた。"},
            {"term": "尊敬する", "reading": "そんけいする", "definition": "尊敬", "mnemonic": "「尊」重並「敬」佩的心情。", "example_sentence": "父のことをとても尊敬している。"},
            {"term": "努力する", "reading": "どりょくする", "definition": "努力", "mnemonic": "用「力」去「努」力達成目標。", "example_sentence": "夢を叶えるために努力している。"},
            {"term": "完成する", "reading": "かんせいする", "definition": "完成", "mnemonic": "「完」全「成」就，大功告成。", "example_sentence": "レポートがやっと完成した。"},
            {"term": "増加する", "reading": "ぞうかする", "definition": "增加", "mnemonic": "數量「増」多，不斷「加」上去。", "example_sentence": "外国人観光客が増加している。"},
            {"term": "減少する", "reading": "げんしょうする", "definition": "減少", "mnemonic": "數量「減」去變「少」了。", "example_sentence": "出生率が年々減少している。"},
            {"term": "変化する", "reading": "へんかする", "definition": "變化", "mnemonic": "事物「変」（變）得不同，產生「化」學反應般的改變。", "example_sentence": "季節の変化を感じる。"},
        ],
    },
    {
        "title": "JLPT N3 - 形容詞・副詞",
        "words": [
            {"term": "正しい", "reading": "ただしい", "definition": "正確的", "mnemonic": "走在「正」道上，方向是對的。", "example_sentence": "正しい答えを選んでください。"},
            {"term": "珍しい", "reading": "めずらしい", "definition": "珍奇的、稀有的", "mnemonic": "王（王）旁邊的寶「珍」，很少見。", "example_sentence": "こんな珍しい花は初めて見た。"},
            {"term": "激しい", "reading": "はげしい", "definition": "激烈的", "mnemonic": "水（氵）流猛烈衝「激」。", "example_sentence": "激しい雨が降ってきた。"},
            {"term": "厳しい", "reading": "きびしい", "definition": "嚴格的", "mnemonic": "「厳」（嚴）肅的態度，不允許馬虎。", "example_sentence": "この先生は成績に厳しい。"},
            {"term": "柔らかい", "reading": "やわらかい", "definition": "柔軟的", "mnemonic": "木頭上長出嫩芽（矛），「柔」軟如棉。", "example_sentence": "このパンはとても柔らかい。"},
            {"term": "固い", "reading": "かたい", "definition": "硬的", "mnemonic": "在「古」老的土地上「固」定不動，很硬。", "example_sentence": "このせんべいは固くて歯が痛い。"},
            {"term": "深い", "reading": "ふかい", "definition": "深的", "mnemonic": "水（氵）下面有個洞穴（穴），很「深」。", "example_sentence": "この川は深いから気をつけて。"},
            {"term": "浅い", "reading": "あさい", "definition": "淺的", "mnemonic": "水（氵）只到很低的地方，很「浅」。", "example_sentence": "ここは浅いから子供でも大丈夫だ。"},
            {"term": "豊か", "reading": "ゆたか", "definition": "豐富的", "mnemonic": "穀物（豆）堆得像山一樣「豊」盛。", "example_sentence": "自然が豊かな場所で暮らしたい。"},
            {"term": "盛ん", "reading": "さかん", "definition": "繁盛的、興盛的", "mnemonic": "把東西「盛」（裝滿）得滿滿的，很興盛。", "example_sentence": "この地域ではサッカーが盛んだ。"},
            {"term": "複雑", "reading": "ふくざつ", "definition": "複雜的", "mnemonic": "「複」數的東西「雑」（雜）在一起，很複雜。", "example_sentence": "この問題は複雑で理解しにくい。"},
            {"term": "単純", "reading": "たんじゅん", "definition": "單純的", "mnemonic": "「単」（單）一又「純」粹，不複雜。", "example_sentence": "答えは意外に単純だった。"},
            {"term": "正確", "reading": "せいかく", "definition": "正確的", "mnemonic": "「正」しく「確」か（確實），毫無錯誤。", "example_sentence": "正確な時間を教えてください。"},
            {"term": "適当", "reading": "てきとう", "definition": "適當的、隨便的", "mnemonic": "「適」合「当」（當）前情況，但也可以是隨便應付。", "example_sentence": "適当なことを言わないでください。"},
            {"term": "必ず", "reading": "かならず", "definition": "一定", "mnemonic": "心（心）中「必」定會實現。", "example_sentence": "約束は必ず守ってください。"},
            {"term": "決して", "reading": "けっして", "definition": "絕對（不）", "mnemonic": "「決」（決定）了絕對不做。", "example_sentence": "このことは決して忘れない。"},
            {"term": "特に", "reading": "とくに", "definition": "特別地", "mnemonic": "「特」別突出的地方。", "example_sentence": "日本料理の中で特にラーメンが好きだ。"},
            {"term": "直接", "reading": "ちょくせつ", "definition": "直接地", "mnemonic": "「直」線地「接」觸，不繞彎。", "example_sentence": "本人に直接聞いた方がいい。"},
            {"term": "突然", "reading": "とつぜん", "definition": "突然", "mnemonic": "像狗（犬）「突」然從穴裡跳出來。", "example_sentence": "突然雨が降り出した。"},
            {"term": "次第に", "reading": "しだいに", "definition": "逐漸地", "mnemonic": "按照「次」序一步步「第」進，逐漸變化。", "example_sentence": "空が次第に暗くなってきた。"},
        ],
    },
]
